.TH "deprecated" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Veraltete Elemente 
.IP "\fBGruppe \fBroomba_stream\fP \fP" 1c
Unbenannt in \fBRoomba Sensor Database\fP
.PP
.IP "\fBGlobal \fBroomba_stream_get\fP (sensorID, result)\fP" 1c
Umbenannt in \fBroomba_sensor_database_get()\fP  
.IP "\fBGlobal \fBroomba_stream_init\fP ()\fP" 1c
Umbenannt in \fBroomba_sensor_database_init()\fP  
.IP "\fBGlobal \fBroomba_stream_receive\fP (data)\fP" 1c
Umbenannt in \fBroomba_sensor_database_receive()\fP 
.PP

