.TH "Roomba Reader" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Roomba Reader \- 
.SS "Makrodefinitionen"

.in +1c
.ti -1c
.RI "#define \fBROOMBA_NONBLOCKING\fP"
.br
.ti -1c
.RI "#define \fBROOMBA_SHORT_READ\fP"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_BUFFER_SIZE\fP   173"
.br
.ti -1c
.RI "#define \fBROOMBA_STREAM_IGNORE\fP   50"
.br
.in -1c
.SS "Typdefinitionen"

.in +1c
.ti -1c
.RI "typedef enum \fBroombaStatus\fP \fBroombaStatus_t\fP"
.br
.in -1c
.SS "Aufzählungen"

.in +1c
.ti -1c
.RI "enum \fBroombaStatus\fP { \fBidle\fP, \fBsingeldata\fP, \fBgroup\fP, \fBquery\fP, \fBstream\fP }"
.br
.in -1c
.SS "Funktionen"

.in +1c
.ti -1c
.RI "int8_t \fBroomba_read\fP (uint8_t c)"
.br
.ti -1c
.RI "int8_t \fBroomba_getSensorData\fP (\fBroombaSensorData_t\fP *data)"
.br
.ti -1c
.RI "void \fBroomba_reset\fP ()"
.br
.ti -1c
.RI "uint8_t \fBroomba_hasSensorData\fP ()"
.br
.ti -1c
.RI "\fBroombaStatus_t\fP \fBroomba_getStatus\fP ()"
.br
.ti -1c
.RI "void \fBroomba_abort_sensor\fP ()"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Lese Module 
.SH "Makro-Dokumentation"
.PP 
.SS "#define ROOMBA_NONBLOCKING"
Wenn dieses Define definiert ist werden alle Blockiere Methoden nicht blockieren und immer \fBROOMBA_ERROR_AGAIN\fP zurückgeben wenn keine Daten verfügbar sind\&.
.PP
Define muss über den Compiler gesetzt werden!(-DROOMBA_NONBLOCKING) 
.SS "#define ROOMBA_SENSOR_BUFFER_SIZE   173"
Roomba Senosr Buffer Größe 
.SS "#define ROOMBA_SHORT_READ"
Wenn diese Define gesetzt ist\&. Wird ein zweiter Ringbuffer vorgeschaltete\&. Ziel ist die Zeit die Read benötigt zu verringern\&.
.PP
Die Daten werden dann nicht mehr von \fBroomba_read()\fP verarbeitet sondern beim Abrufen der Daten(\fBroomba_hasSensorData()\fP und \fBroomba_getSensorData\fP)
.PP
Define muss über den Compiler gesetzt werden!(-DROOMBA_SHORT_READ) 
.SS "#define ROOMBA_STREAM_IGNORE   50"
Anzahl von Stream Paketen die Ignoriert werden sollen falls der Interne Buffer voll ist 
.SH "Dokumentation der benutzerdefinierten Typen"
.PP 
.SS "typedef enum \fBroombaStatus\fP \fBroombaStatus_t\fP"

.SH "Dokumentation der Aufzählungstypen"
.PP 
.SS "enum \fBroombaStatus\fP"
Stadien für lesen 
.PP
\fBAufzählungswerte\fP
.in +1c
.TP
\fB\fIidle \fP\fP
Idle 
.TP
\fB\fIsingeldata \fP\fP
Singeldata 
.TP
\fB\fIgroup \fP\fP
Gruppe 
.TP
\fB\fIquery \fP\fP
Query List 
.TP
\fB\fIstream \fP\fP
stream 
.SH "Dokumentation der Funktionen"
.PP 
.SS "void roomba_abort_sensor ()"
Bricht Sensor Pasing ab
.PP
Es kann vorkommen das nicht alle Pakete eines angeforderten Befehles ankommen daher ist es wichtig das auch ein Sensor Befehl abgebrochen werden kann
.PP
Falls aktuell kein Sensor Befehl aktiv ist hat dieser Befehl keine Auswirkung!
.PP
Diese Funktion setzt den Fehler \fBROOMBA_ERROR_ABORT_SENSOR\fP
.PP
Falls ein Sensor Stream aktiv ist wird dieser mit dem Befehl \fBROOMBA_STREAM_PAUSE_RESUME\fP beendet 
.SS "int8_t roomba_getSensorData (\fBroombaSensorData_t\fP *data)"
Gibt ein Sensor Daten zurück Wenn keine Daten verfügbar sind blockiert diese Methode bis Daten da sind(Ausser \fBROOMBA_NONBLOCKING\fP ist gesetzt!)
.PP
\fBParameter:\fP
.RS 4
\fIdata\fP Rommba Sensor Daten 
.RE
.PP
\fBRückgabe:\fP
.RS 4
Folge Werne können zurück geben werden:
.IP "\(bu" 2
\fB0\fP kein Fehler
.IP "\(bu" 2
\fB-\fBROOMBA_ERROR_AGAIN\fP\fP Keine SensorDaten vorhanden! Wird nur zurück geben wenn \fBROOMBA_NONBLOCKING\fP gesetzt ist! 
.PP
.RE
.PP

.SS "\fBroombaStatus_t\fP roomba_getStatus ()"
Gibt Aktuellen Sensor Paser Status zurück
.PP
\fBRückgabe:\fP
.RS 4
Status 
.RE
.PP

.SS "uint8_t roomba_hasSensorData ()"
Prüft ob SensorDaten vorliegen
.PP
\fBRückgabe:\fP
.RS 4
true: SensorDaten verfügbar false: Keine SensorDaten verfügbar 
.RE
.PP

.SS "int8_t roomba_read (uint8_tc)"
Verarbeite ein Zeichen
.PP
\fBParameter:\fP
.RS 4
\fIc\fP Zeichen das Verarbeitet werden soll 
.RE
.PP
\fBRückgabe:\fP
.RS 4
Kann verschiedene Werte zurückgeben
.IP "\(bu" 2
\fB0\fP Kein Fehler
.IP "\(bu" 2
\fB-\fBROOMBA_ERROR_BUFFER_FULL\fP(-\fBROOMBA_ERROR_BUFFER_FULL_CHAR\fP, -\fBROOMBA_ERROR_BUFFER_FULL_STREAM\fP)\fP Buffer voll
.IP "\(bu" 2
\fB-\fBROOMBA_ERROR_NO_SIGN_EXPECTED\fP\fP Kein Zeichen erwartet Beim verarbeiten eines Stream können folgende (Fehler auftreten Fehler kännen nur auftreten wenn \fBROOMBA_SHORT_READ\fP nicht gesetzt ist!)
.IP "\(bu" 2
\fB-\fBROOMBA_ERROR_HEADER_NOT_FOUND\fP\fP Zeichen war nicht das erwarte Header Zeichen(19)
.IP "\(bu" 2
\fB-\fBROOMBA_ERROR_SENSORID_NOT_FOUND\fP\fP Senesor ID nicht korrekt
.IP "\(bu" 2
\fB-\fBROOMBA_ERROR_CHECKSUM_NOT_VALID\fP\fP Checksumme nicht korrekt 
.PP
.RE
.PP

.SS "void roomba_reset ()"
Resetet Buffer 
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Roomba Library aus dem Quellcode\&.
