.TH "Roomba Reader/Writer" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Roomba Reader/Writer \- 
.SS "Module"

.in +1c
.ti -1c
.RI "\fBRoomba Reader\fP"
.br
.ti -1c
.RI "\fBRoomba Writer\fP"
.br
.in -1c
.SS "Funktionen"

.in +1c
.ti -1c
.RI "void \fBroomba_init\fP (int(*w)(unsigned char c))"
.br
.ti -1c
.RI "int8_t \fBroomba_getError\fP ()"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Roomba Reader / Writer Module
.PP
Dieses Modules ist für die Kommunikation mit dem Roomba verantwortlich\&. 
.SH "Dokumentation der Funktionen"
.PP 
.SS "int8_t roomba_getError ()"
Gibt den ersten Fehler zurück Falls kein Fehler aufgetreten ist wird \fBROOMBA_ERROR_NO\fP zurückgeben Der Fehler wird nach dem Lesen auf \fBROOMBA_ERROR_NO\fP zurückgesetzt\&. 
.PP
\fBRückgabe:\fP
.RS 4
gibt die Aktuelle Fehlernummer zurück oder \fBROOMBA_ERROR_NO\fP 
.RE
.PP

.SS "void roomba_init (int(*)(unsigned char c)w)"
Roomba Init 
.PP
\fBParameter:\fP
.RS 4
\fIw\fP Callback um ein Zeichen zu schreiben 
.RE
.PP

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Roomba Library aus dem Quellcode\&.
