.TH "/home/andreas/roomba/lib/includes/roomba_print.h" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/andreas/roomba/lib/includes/roomba_print.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <roomba_def\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br

.SS "Datenstrukturen"

.in +1c
.ti -1c
.RI "struct \fBsensorString\fP"
.br
.ti -1c
.RI "struct \fBcommandString\fP"
.br
.in -1c
.SS "Makrodefinitionen"

.in +1c
.ti -1c
.RI "#define \fBGET_SENSOR_STRING\fP(i)   \fBsensorStrings\fP[i]\&.sensorStr"
.br
.ti -1c
.RI "#define \fBGET_SENSOR_STRING_SIZE\fP()   \fBsensorStringSize\fP"
.br
.ti -1c
.RI "#define \fBGET_COMMAND_STRING\fP(i)   \fBcommandStrings\fP[i-\fBROOMBA_START\fP]\&.commandStr"
.br
.ti -1c
.RI "#define \fBGET_COMMAND_STRING_SIZE\fP()   \fBcommandStringSize\fP"
.br
.in -1c
.SS "Typdefinitionen"

.in +1c
.ti -1c
.RI "typedef struct \fBsensorString\fP \fBsensorString_t\fP"
.br
.ti -1c
.RI "typedef struct \fBcommandString\fP \fBcommandString_t\fP"
.br
.in -1c
.SS "Funktionen"

.in +1c
.ti -1c
.RI "void \fBroomba_printSensorData\fP (\fBroombaSensorData_t\fP *data)"
.br
.ti -1c
.RI "void \fBroomba_printCommand\fP (\fBroombaCommand_t\fP *c)"
.br
.in -1c
.SS "Variablen"

.in +1c
.ti -1c
.RI "\fBsensorString_t\fP \fBsensorStrings\fP []"
.br
.ti -1c
.RI "const size_t \fBsensorStringSize\fP"
.br
.ti -1c
.RI "\fBcommandString_t\fP \fBcommandStrings\fP []"
.br
.ti -1c
.RI "const size_t \fBcommandStringSize\fP"
.br
.in -1c
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Roomba Library aus dem Quellcode\&.
