.TH "Roomba Stream Libary(deprecated)" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Roomba Stream Libary(deprecated) \- 
.SS "Makrodefinitionen"

.in +1c
.ti -1c
.RI "#define \fBroomba_stream_init\fP()   \fBroomba_sensor_database_init\fP()"
.br
.ti -1c
.RI "#define \fBroomba_stream_receive\fP(data)   \fBroomba_sensor_database_receive\fP(data)"
.br
.ti -1c
.RI "#define \fBroomba_stream_get\fP(sensorID, result)   \fBroomba_sensor_database_get\fP(sensorID, result)"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
\fBVeraltet\fP
.RS 4
Unbenannt in \fBRoomba Sensor Database\fP
.RE
.PP

.SH "Makro-Dokumentation"
.PP 
.SS "#define roomba_stream_get(sensorID, result)   \fBroomba_sensor_database_get\fP(sensorID, result)"
\fBSiehe auch:\fP
.RS 4
\fBroomba_sensor_database_get()\fP 
.RE
.PP
\fBVeraltet\fP
.RS 4
Umbenannt in \fBroomba_sensor_database_get()\fP 
.RE
.PP

.SS "#define roomba_stream_init()   \fBroomba_sensor_database_init\fP()"
\fBSiehe auch:\fP
.RS 4
\fBroomba_sensor_database_init()\fP 
.RE
.PP
\fBVeraltet\fP
.RS 4
Umbenannt in \fBroomba_sensor_database_init()\fP 
.RE
.PP

.SS "#define roomba_stream_receive(data)   \fBroomba_sensor_database_receive\fP(data)"
\fBSiehe auch:\fP
.RS 4
\fBroomba_sensor_database_receive()\fP 
.RE
.PP
\fBVeraltet\fP
.RS 4
Umbenannt in \fBroomba_sensor_database_receive()\fP 
.RE
.PP

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Roomba Library aus dem Quellcode\&.
