.TH "Globale Roomba Definitionen" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Globale Roomba Definitionen \- 
.SS "Module"

.in +1c
.ti -1c
.RI "\fBRoomba Error\fP"
.br
.ti -1c
.RI "\fBRoomba Kommandos\fP"
.br
.ti -1c
.RI "\fBSensor Daten\fP"
.br
.in -1c
.SS "Datenstrukturen"

.in +1c
.ti -1c
.RI "struct \fBroombaCommand\fP"
.br
.ti -1c
.RI "struct \fBroombaSensorData\fP"
.br
.in -1c
.SS "Makrodefinitionen"

.in +1c
.ti -1c
.RI "#define \fBROOMBA_MAX_DATA\fP   66"
.br
.in -1c
.SS "Typdefinitionen"

.in +1c
.ti -1c
.RI "typedef struct \fBroombaCommand\fP \fBroombaCommand_t\fP"
.br
.ti -1c
.RI "typedef struct \fBroombaSensorData\fP \fBroombaSensorData_t\fP"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Alle globalen Definitionen für die Roomba Libary
.PP
Das sind alle Globalen Roomba Definitionen 
.SH "Makro-Dokumentation"
.PP 
.SS "#define ROOMBA_MAX_DATA   66"
Maximale Anzahl von Daten die ein Kommando enthalten kann 
.SH "Dokumentation der benutzerdefinierten Typen"
.PP 
.SS "typedef struct \fBroombaCommand\fP \fBroombaCommand_t\fP"

.SS "typedef struct \fBroombaSensorData\fP \fBroombaSensorData_t\fP"

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Roomba Library aus dem Quellcode\&.
