.TH "Interne Sensor Daten" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Interne Sensor Daten \- 
.SS "Makrodefinitionen"

.in +1c
.ti -1c
.RI "#define \fBROOMBA_SENSOR_CHANGING_STATE\fP   21"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_VOLTAGE\fP   22"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_CURRENT\fP   23"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_TEMPERATURE\fP   24"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_BATTERY_CHARGE\fP   25"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_BATTERY_CAPACITY\fP   26"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_CHARGING_SOURCES_AVAILABLE\fP   34"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_OI_MODE\fP   35"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_SONG_NUMBER\fP   36"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_SONG_PLAYING\fP   37"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_NUMBER_STREAM_PACKETS\fP   38"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_MOTOR_CURRENT_LEFT\fP   54"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_MOTOR_CURRENT_RIGHT\fP   55"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_MOTOR_BRUSH_MAIN\fP   56"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_MOTOR_BRUSH_SIDE\fP   57"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SH "Makro-Dokumentation"
.PP 
.SS "#define ROOMBA_SENSOR_BATTERY_CAPACITY   26"
Zeigt die Aktuelle Ladung der Batterie an in Milliampere Stunden\&. Gibt einen 16-Bit Wert von 0 - 65535 mAh zurück\&. Syntax: [26] [High Byte] [Low byte] 
.SS "#define ROOMBA_SENSOR_BATTERY_CHARGE   25"
Aktuelle lade Wert in Milliampere Stunden\&. Gibt einen 16 Bit Wert von 0 - 65535 mAh zurück\&. Syntax: [25] [High Byte] [Low byte] 
.SS "#define ROOMBA_SENSOR_CHANGING_STATE   21"
Zeigt den Status des Lade Zyklus an\&. 0 = Lädt nicht 1 = Wiederauffrisch- Ladezyklus 2 = Aufgeladen 3 = Entladung 4 = Warten 5 = Fehler beim Laden 
.SS "#define ROOMBA_SENSOR_CHARGING_SOURCES_AVAILABLE   34"
Gibt an welche Strom Quelle aktuell angeschlossen ist\&. Gibt eine 8- Bit Maske zurück Syntax Reserved&Reserved&Reserved&Reserved&Reserved&Reserved&Home Base&Inernal Changer Syntax: [34] [Bit Mask] 
.SS "#define ROOMBA_SENSOR_CURRENT   23"
Zeigt den Aktuellen Verbrauch Milliampere an\&. Ein negativer Wert zeigt an das die Spannungsquelle belastet wird(Normal Betrieb) und ein positiver Wert zeigt an das die Spannungsquelle geladen wird\&. 
.SS "#define ROOMBA_SENSOR_MOTOR_BRUSH_MAIN   56"
Aktueller Strom Verbrauch des Staubsaugmotors\&. Liefert ein 16 Bit Wert zwischen -32768 – 32767 mA zurück Syntax [53] [High Byte] [Low Byte] 
.SS "#define ROOMBA_SENSOR_MOTOR_BRUSH_SIDE   57"
Aktueller Strom Verbrauch des Seitlichen Staubsaugmotors\&. Liefert ein 16 Bit Wert zwischen -32768 – 32767 mA zurück Syntax [53] [High Byte] [Low Byte] 
.SS "#define ROOMBA_SENSOR_MOTOR_CURRENT_LEFT   54"
Aktueller Strom Verbrauch des Linken Motors\&. Liefert ein 16 Bit Wert zwischen -32768 – 32767 mA zurück Syntax [52] [High Byte] [Low Byte] 
.SS "#define ROOMBA_SENSOR_MOTOR_CURRENT_RIGHT   55"
Aktueller Strom Verbrauch des Rechten Motors\&. Liefert ein 16 Bit Wert zwischen -32768 – 32767 mA zurück Syntax [53] [High Byte] [Low Byte] 
.SS "#define ROOMBA_SENSOR_NUMBER_STREAM_PACKETS   38"
Gibt die aktuelle Nummer des Stream Paketes zurück\&. Es kann ein Wert von 0-108 zurück 
.SS "#define ROOMBA_SENSOR_OI_MODE   35"
Gibt den Aktuellen OI Modus zurück\&. 0 = Off 1 = Passive 2 = Safe 3 = Full 
.SS "#define ROOMBA_SENSOR_SONG_NUMBER   36"
Gibt die Aktuelle Song Nummer an die Aktuell abgespielt wird\&. Wert von 0 - 15 
.SS "#define ROOMBA_SENSOR_SONG_PLAYING   37"
Gibt zurück ob aktuell ein Song abgespielt wird oder nicht\&. 0 = kein Song wird abgespielt 1 = Song wird abgespielt 
.SS "#define ROOMBA_SENSOR_TEMPERATURE   24"
Zeigt die Temperatur in Grad Celsius der Batterie an\&. Wert von -128 - 127 
.SS "#define ROOMBA_SENSOR_VOLTAGE   22"
Zeigt die Aktuelle Spannung der Quelle an in Millivolt\&. Übertragen wird ein 16 Bit Wert von 0 - 65535 mV Syntax [22] [High Byte] [Low byte] 
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Roomba Library aus dem Quellcode\&.
