.TH "Roomba Reepeat Libary" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Roomba Reepeat Libary \- 
.SS "Makrodefinitionen"

.in +1c
.ti -1c
.RI "#define \fBROOMBA_REPEAT_ERROR_NOT_STARTED\fP   -2"
.br
.in -1c
.SS "Funktionen"

.in +1c
.ti -1c
.RI "int8_t \fBroomba_repeat_init\fP (int8_t(*c)(\fBroombaCommand_t\fP *command), int8_t(*thread_start)(uint16_t ms), int8_t(*thread_stop)())"
.br
.ti -1c
.RI "int8_t \fBroomba_repeat\fP ()"
.br
.ti -1c
.RI "int8_t \fBroomba_repeat_start\fP (\fBroombaCommand_t\fP *c, uint16_t ms)"
.br
.ti -1c
.RI "int8_t \fBroomba_repeat_stop\fP ()"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Definiert eine API um eine Befehl zyklisch immer wieder auszuführen\&. 
.SH "Makro-Dokumentation"
.PP 
.SS "#define ROOMBA_REPEAT_ERROR_NOT_STARTED   -2"
Thread konnte nicht gestartet werden 
.SH "Dokumentation der Funktionen"
.PP 
.SS "int8_t roomba_repeat ()"
Funktion die immer wieder aufgerufen werden muss Diese Funktion sendet das mit \fBroomba_repeat_start\fP definiert Kommando Diese Funktion muss von dem Thread aufgerufen werden
.PP
\fBRückgabe:\fP
.RS 4
Funktion kann folgende Werte zurückgeben:
.IP "\(bu" 2
0 kein Fehler
.IP "\(bu" 2
\fB\fBROOMBA_REPEAT_ERROR_NOT_STARTED\fP\fP System ist nicht gestartet 
.PP
.RE
.PP

.SS "int8_t roomba_repeat_init (int8_t(*)(\fBroombaCommand_t\fP *command)c, int8_t(*)(uint16_t ms)thread_start, int8_t(*)()thread_stop)"
Initialisiert Repeat Libaray
.PP
\fBParameter:\fP
.RS 4
\fIc\fP Sende Funktion Vergleichbar mit \fBroomba_command_init\fP 
.br
\fIthread_start\fP Funktion die einen Thread startet der alle ms die Funktion \fBroomba_repeat\fP aufruft\&. 
.br
\fIthread_stop\fP Funktion die den Thread Stoppt 
.RE
.PP
\fBRückgabe:\fP
.RS 4
0 kein Fehler Aufgetreten 
.RE
.PP

.SS "int8_t roomba_repeat_start (\fBroombaCommand_t\fP *c, uint16_tms)"
Sendet alle ms Millisekunde den Befehl c
.PP
Falls bereits ein Befehl gestartet worden ist wird dieser gestoppt
.PP
\fBParameter:\fP
.RS 4
\fIc\fP Befehl der gesendet werden soll 
.br
\fIms\fP Zeit in Millisekunde die der Befehl wiederholte werden soll 
.RE
.PP
\fBRückgabe:\fP
.RS 4
< 0 Fehler sonst kein Fehler 
.RE
.PP

.SS "int8_t roomba_repeat_stop ()"
Stoppt Thread wieder 
.PP
\fBRückgabe:\fP
.RS 4
< 0 Fehler sonst kein Fehler 
.RE
.PP

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Roomba Library aus dem Quellcode\&.
