.TH "Stream Fehler" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stream Fehler \- 
.SS "Makrodefinitionen"

.in +1c
.ti -1c
.RI "#define \fBROOMBA_ERROR_HEADER_NOT_FOUND\fP   0x05"
.br
.ti -1c
.RI "#define \fBROOMBA_ERROR_SENSORID_NOT_FOUND\fP   0x06"
.br
.ti -1c
.RI "#define \fBROOMBA_ERROR_CHECKSUM_NOT_VALID\fP   0x07"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SH "Makro-Dokumentation"
.PP 
.SS "#define ROOMBA_ERROR_CHECKSUM_NOT_VALID   0x07"
Checksum nicht gueltig 
.SS "#define ROOMBA_ERROR_HEADER_NOT_FOUND   0x05"
Header Nicht gefunden 
.SS "#define ROOMBA_ERROR_SENSORID_NOT_FOUND   0x06"
SensorID nicht korrekt 
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Roomba Library aus dem Quellcode\&.
