.TH "/home/andreas/roomba/lib/includes/roomba.h" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/andreas/roomba/lib/includes/roomba.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <roomba_def\&.h>\fP
.br

.SS "Makrodefinitionen"

.in +1c
.ti -1c
.RI "#define \fBROOMBA_NONBLOCKING\fP"
.br
.ti -1c
.RI "#define \fBROOMBA_SHORT_READ\fP"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_BUFFER_SIZE\fP   173"
.br
.ti -1c
.RI "#define \fBROOMBA_STREAM_IGNORE\fP   50"
.br
.in -1c
.SS "Typdefinitionen"

.in +1c
.ti -1c
.RI "typedef enum \fBroombaStatus\fP \fBroombaStatus_t\fP"
.br
.in -1c
.SS "Aufzählungen"

.in +1c
.ti -1c
.RI "enum \fBroombaStatus\fP { \fBidle\fP, \fBsingeldata\fP, \fBgroup\fP, \fBquery\fP, \fBstream\fP }"
.br
.in -1c
.SS "Funktionen"

.in +1c
.ti -1c
.RI "void \fBroomba_init\fP (int(*w)(unsigned char c))"
.br
.ti -1c
.RI "int8_t \fBroomba_read\fP (uint8_t c)"
.br
.ti -1c
.RI "int8_t \fBroomba_getSensorData\fP (\fBroombaSensorData_t\fP *data)"
.br
.ti -1c
.RI "void \fBroomba_reset\fP ()"
.br
.ti -1c
.RI "int8_t \fBroomba_sendCommand\fP (\fBroombaCommand_t\fP *c)"
.br
.ti -1c
.RI "uint8_t \fBroomba_hasSensorData\fP ()"
.br
.ti -1c
.RI "int8_t \fBroomba_getError\fP ()"
.br
.ti -1c
.RI "\fBroombaStatus_t\fP \fBroomba_getStatus\fP ()"
.br
.ti -1c
.RI "void \fBroomba_abort_sensor\fP ()"
.br
.in -1c
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Roomba Library aus dem Quellcode\&.
