.TH "/home/andreas/roomba/lib/includes/roomba_sensor_database.h" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/andreas/roomba/lib/includes/roomba_sensor_database.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <roomba_def\&.h>\fP
.br

.SS "Funktionen"

.in +1c
.ti -1c
.RI "int8_t \fBroomba_sensor_database_init\fP ()"
.br
.ti -1c
.RI "int8_t \fBroomba_sensor_database_receive\fP (\fBroombaSensorData_t\fP *data)"
.br
.ti -1c
.RI "int8_t \fBroomba_sensor_database_get\fP (uint8_t sensorID, \fBroombaSensorData_t\fP *result)"
.br
.in -1c
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Roomba Library aus dem Quellcode\&.
