.TH "Motor Steuerungskommandos" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Motor Steuerungskommandos \- 
.SS "Makrodefinitionen"

.in +1c
.ti -1c
.RI "#define \fBROOMBA_DRIVE\fP   137"
.br
.ti -1c
.RI "#define \fBROOMBA_DRIVE_DIRECT\fP   145"
.br
.ti -1c
.RI "#define \fBROOMBA_DRIVE_PWM\fP   146"
.br
.ti -1c
.RI "#define \fBROOMBA_MOTORS\fP   138"
.br
.ti -1c
.RI "#define \fBROOMBA_MOTORS_PWM\fP   144"
.br
.ti -1c
.RI "#define \fBROOMBA_LEDS\fP   139"
.br
.ti -1c
.RI "#define \fBROOMBA_LEDS_SCHEDULING\fP   162"
.br
.ti -1c
.RI "#define \fBROOMBA_LEDS_DIGIT_RAW\fP   163"
.br
.ti -1c
.RI "#define \fBROOMBA_LEDS_DIGIT_ASCII\fP   164"
.br
.ti -1c
.RI "#define \fBROOMBA_BUTTONS\fP   165"
.br
.ti -1c
.RI "#define \fBROOMBA_SONG\fP   140"
.br
.ti -1c
.RI "#define \fBROOMBA_PLAY\fP   141"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SH "Makro-Dokumentation"
.PP 
.SS "#define ROOMBA_BUTTONS   165"
Mit diesem Befehl können die Knöpfe des Roombas gedrückt werden\&. Hiebei wird ebenfalls eine 8-Bit Maske verwendet\&. Syntax: Clock&Schedule&Day&Hour&Minute&Dock&Spot&Clean Syntax: [165] [Buttons] 
.SS "#define ROOMBA_DRIVE   137"
Startet Bewegung Syntax Syntax: [Velocity high byte] [Velocity low byte] [Radius high byte] [Radius low byte] Velocity (-500 - 500 mm/s) Radius (-2000 - 2000 mm) 
.SS "#define ROOMBA_DRIVE_DIRECT   145"
Motoren Einzel Steuern Syntax: [Right velocity high byte] [Right velocity low byte] [Left velocity high byte] [Left velocity low byte]
.PP
Auf dem Roomba 780 dm/s nicht mm/s 
.SS "#define ROOMBA_DRIVE_PWM   146"
Steuert die Motoren über PWM direkt an Syntax:[Right PWM high byte] [Right PWM low byte] [Left PWM high byte] [Left PWM low byte] 
.SS "#define ROOMBA_LEDS   139"
Steuert alle LEDs des Roombars\&. Welche der LEDs hierbei leuchten sollen wird ebenfalls über eine 8-Bit Maske festgelegte\&. Syntax: Reserved&Reserved&Reserved&Reserved&Check Robot&Dock&Spot&Debris\&. Danach folgt Die Fabe der Power LED und die helligkeit\&. Syntax: [139] [LED Bits] [Clean/Power Color] [Clean/Power Intensity] 
.SS "#define ROOMBA_LEDS_DIGIT_ASCII   164"
Hier kann die Siebensegment Anzeige gesteuert werden\&. Hierbei werden die einzelne Siebensegment Anzeigen mit hilf von ASCII Zeichen gesteuert\&. Diese müssen nicht unbedingt korrekt angezeigt werden\&. Die Zeichen von ASCII Zeichen 32 bis 126 werden von Roomba verstanden und angezeigt(Alle Großbuchstaben + Sonderzeichen) Syntax: [164] [Digit 3 ASCII] [Digit 2 ASCII] [Digit 1 ASCII] [Digit 0 ASCII] 
.SS "#define ROOMBA_LEDS_DIGIT_RAW   163"
Hier kann die Siebensegment anzeige des Roombars gesteuert werden\&. Es gibt hierbei 4 Siebensegment Anzeigen die über eine 8-Bit Maske gesteuert wird Syntax: Reserved&GF&E&D&CB&A Syntax: [163] [Digit 3 Bits] [Digit 2 Bits] [Digit 1 Bits] [Digit 0 Bits] 
.SS "#define ROOMBA_LEDS_SCHEDULING   162"
Streut die oberen LEDs\&. Diese sind für die Anzeige des Zeitplanes zuständig\&. Hierbei kann über eine 8-Bit Maske die Wochentags LEDs gesteuert werden Syntax: Reserved&Sat&Fri&Thu&Wed&Tue&Mon&Sun\&. Danach könenn noch 5 weiter LEDs über eine 8-Bit Maske gesteuert werden: Reserved&Reserved&Reserved&Schedule&Clock&AM&PM&Colon(:) Syntax: [162] [Weekday LED Bits][Scheduling LED Bits] 
.SS "#define ROOMBA_MOTORS   138"
Aktiviert die Motoren für die Reinigung(Sauger hier inbegriffen)\&. Dieser Befehl aktiviert den Motor mit voller Leistung\&. Welcher Motor hierbei eingeschaltet wird oder welche Richtung wird über eine 8 Bit Bitmaske gesetzt\&. Syntax: Reserved&Reserved&Reserved&Main Brush Direction&Side Bruch Clockwiese&Main Brush&Vacuum&Side Brush 
.SS "#define ROOMBA_MOTORS_PWM   144"
Direkte PWM Steuerung der Reinigungsmotoren\&.Syntax: [144] [Main Brush PWM] [Side Brush PWM] [Vacuum PWM] 
.SS "#define ROOMBA_PLAY   141"
Spielt einen gespeicherten Song ab Syntax: [141] [Song Number] 
.SS "#define ROOMBA_SONG   140"
140 Dieser Befehl ermöglicht es bis zu 4 Musikstücke auf dem Roomba zu Speichern\&. Jedes Musikstück kann bis zu 16 Noten enthalten\&. Die Noten werden hierbei im MIDI Standart definiert\&. Der Roomba unterstützt die Noten 31-127\&. Zusätzlich muss zu einer Note noch die Abspielzeit der Note übertragen werden\&. Diese muss in einer Zahl von 1-255 übertragen werden\&. 1 entspricht hierbei 1/64 Sekunden\&. [140] [Song Number] [Song Length] [Note Number 1] [Note Duration 1] [Note Number 2] [Note Duration 2], etc\&. 
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Roomba Library aus dem Quellcode\&.
