.TH "Script Events" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Script Events \- 
.SS "Makrodefinitionen"

.in +1c
.ti -1c
.RI "#define \fBROOMBA_EVNET_WHEEL_DROP\fP   1"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_WHEEL_DROP_FRONT\fP   2"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_WHEEL_DROP_LEFT\fP   3"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_WHEEL_DROP_RIGHT\fP   4"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_BUMP\fP   5"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_BUMP_LEFT\fP   6"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_BUMP_RIGHT\fP   7"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_VIRTUAL_WALL\fP   8"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_WALL\fP   9"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_CLIFF\fP   10"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_CLIFF_LEFT\fP   11"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_CLIFF_FRONT_LEFT\fP   12"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_CLIFF_FRONT_RIGHT\fP   13"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_CLIFF_RIGHT\fP   14"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_HOME_BASE\fP   15"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_ADVANCE_BUTTON\fP   16"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_PLAY_BUTTON\fP   17"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_DIGITAL_INPUT_0\fP   18"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_DIGITAL_INPUT_1\fP   19"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_DIGITAL_INPUT_2\fP   20"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_DIGITAL_INPUT_3\fP   21"
.br
.ti -1c
.RI "#define \fBROOMBA_EVNET_OI_MODE_PASSIVE\fP   22"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Events für \fBROOMBA_WAIT_EVENT\fP 
.SH "Makro-Dokumentation"
.PP 
.SS "#define ROOMBA_EVNET_ADVANCE_BUTTON   16"

.SS "#define ROOMBA_EVNET_BUMP   5"

.SS "#define ROOMBA_EVNET_BUMP_LEFT   6"

.SS "#define ROOMBA_EVNET_BUMP_RIGHT   7"

.SS "#define ROOMBA_EVNET_CLIFF   10"

.SS "#define ROOMBA_EVNET_CLIFF_FRONT_LEFT   12"

.SS "#define ROOMBA_EVNET_CLIFF_FRONT_RIGHT   13"

.SS "#define ROOMBA_EVNET_CLIFF_LEFT   11"

.SS "#define ROOMBA_EVNET_CLIFF_RIGHT   14"

.SS "#define ROOMBA_EVNET_DIGITAL_INPUT_0   18"

.SS "#define ROOMBA_EVNET_DIGITAL_INPUT_1   19"

.SS "#define ROOMBA_EVNET_DIGITAL_INPUT_2   20"

.SS "#define ROOMBA_EVNET_DIGITAL_INPUT_3   21"

.SS "#define ROOMBA_EVNET_HOME_BASE   15"

.SS "#define ROOMBA_EVNET_OI_MODE_PASSIVE   22"

.SS "#define ROOMBA_EVNET_PLAY_BUTTON   17"

.SS "#define ROOMBA_EVNET_VIRTUAL_WALL   8"

.SS "#define ROOMBA_EVNET_WALL   9"

.SS "#define ROOMBA_EVNET_WHEEL_DROP   1"

.SS "#define ROOMBA_EVNET_WHEEL_DROP_FRONT   2"

.SS "#define ROOMBA_EVNET_WHEEL_DROP_LEFT   3"

.SS "#define ROOMBA_EVNET_WHEEL_DROP_RIGHT   4"

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Roomba Library aus dem Quellcode\&.
