.TH "Roomba Error" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Roomba Error \- 
.SS "Module"

.in +1c
.ti -1c
.RI "\fBStream Fehler\fP"
.br
.in -1c
.SS "Makrodefinitionen"

.in +1c
.ti -1c
.RI "#define \fBROOMBA_ERROR_NO\fP   0x00"
.br
.ti -1c
.RI "#define \fBROOMBA_ERROR_BUFFER_FULL\fP   0x01"
.br
.ti -1c
.RI "#define \fBROOMBA_ERROR_NO_SIGN_EXPECTED\fP   0x02"
.br
.ti -1c
.RI "#define \fBROOMBA_ERROR_WRITE\fP   0x03"
.br
.ti -1c
.RI "#define \fBROOMBA_ERROR_TO_BIG\fP   0x04"
.br
.ti -1c
.RI "#define \fBROOMBA_ERROR_AGAIN\fP   0x08"
.br
.ti -1c
.RI "#define \fBROOMBA_ERROR_BUFFER_FULL_STREAM\fP   0x09"
.br
.ti -1c
.RI "#define \fBROOMBA_ERROR_BUFFER_FULL_CHAR\fP   0x0a"
.br
.ti -1c
.RI "#define \fBROOMBA_ERROR_CALIBRATION_FAULT\fP   0x0b"
.br
.ti -1c
.RI "#define \fBROOMBA_ERROR_ABORT_SENSOR\fP   0x0c"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Alle Fehler die auftreten können
.PP
Fehler werden über Roomba Contol ID \fBROOMBA_CONTOLID_ERROR\fP vom Sensorknoten übermittelt 
.SH "Makro-Dokumentation"
.PP 
.SS "#define ROOMBA_ERROR_ABORT_SENSOR   0x0c"
Sensor Befehl abgebrochen 
.SS "#define ROOMBA_ERROR_AGAIN   0x08"
Wird zurückgeben wenn keine Daten vorliegen oder der Send Befehl nicht gesendet werden kann weil noch Daten erwartet werden
.PP
error Variable wird nicht gesetzt!
.PP
Wird nur zurückgeben wenn ROOMBA_NONBLOCKING gesetzt ist! 
.SS "#define ROOMBA_ERROR_BUFFER_FULL   0x01"
Buffer Voll 
.SS "#define ROOMBA_ERROR_BUFFER_FULL_CHAR   0x0a"
Char Ringbuffer voll gelaufen
.PP
Kann nur eintreten wenn \fBROOMBA_SHORT_READ\fP gesetzt ist 
.SS "#define ROOMBA_ERROR_BUFFER_FULL_STREAM   0x09"
Buffer Voll beim lesen eines Streames Tritt nur auf wenn nach der Ignore Phase der Buffer immer noch Voll ist 
.PP
\fBSiehe auch:\fP
.RS 4
\fBROOMBA_STREAM_IGNORE\fP 
.RE
.PP

.SS "#define ROOMBA_ERROR_CALIBRATION_FAULT   0x0b"
Kalibrierung auf Roomba Fehlgeschlagen
.PP
Verbindung zum Roomba gestört! 
.SS "#define ROOMBA_ERROR_NO   0x00"
Kein Fehler 
.SS "#define ROOMBA_ERROR_NO_SIGN_EXPECTED   0x02"
Kein Zeichen erwartet 
.SS "#define ROOMBA_ERROR_TO_BIG   0x04"
Anfrage ist nach dem expandieren der Gruppen zu Gross 
.SS "#define ROOMBA_ERROR_WRITE   0x03"
Write Error 
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Roomba Library aus dem Quellcode\&.
