.TH "Roomba Contol" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Roomba Contol \- 
.SS "Makrodefinitionen"

.in +1c
.ti -1c
.RI "#define \fBROOMBA_CONTOLID_ERROR\fP   0x01"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Dieses Modul definerit IDs für das Roomba Contol System
.PP
Das Roomba Contoll System ist für die erweitere Kontolle des Sensorknoten gedacht Der Sensorknoten sendet über die Contol Nachrichten Aufgetrete Fehler 
.SH "Makro-Dokumentation"
.PP 
.SS "#define ROOMBA_CONTOLID_ERROR   0x01"
Fehler auf dem Sensorknoten
.PP
Im Data Teil ist der Fehler enthalten 
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Roomba Library aus dem Quellcode\&.
