.TH "Sensor Kommandos" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sensor Kommandos \- 
.SS "Makrodefinitionen"

.in +1c
.ti -1c
.RI "#define \fBROOMBA_SENSORS\fP   142"
.br
.ti -1c
.RI "#define \fBROOMBA_QUERY_LIST\fP   149"
.br
.ti -1c
.RI "#define \fBROOMBA_STREAM\fP   148"
.br
.ti -1c
.RI "#define \fBROOMBA_STREAM_PAUSE_RESUME\fP   150"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SH "Makro-Dokumentation"
.PP 
.SS "#define ROOMBA_QUERY_LIST   149"
Lifert eine Liste von Sensor Daten Syntax: [149][Number of Packets][Packet ID 1][Packet ID 2]\&.\&.\&.[Packet ID N] 
.SS "#define ROOMBA_SENSORS   142"
Ruft einen Bestimmten Sensor ab\&. Ein Wert von 100 liefert alle Sensor Daten\&. 
.SS "#define ROOMBA_STREAM   148"
Liefert eine Liste von Sensor Daten die Alle 15ms wiederholt wird\&. Die Checksum ist die Summe alle Bytes nach dem Header\&. Das Low-Byte der Summe plus die Checksum muss 0 sein((checksum+summe)%0xFF == 0)\&. Wenn mehr Daten angefordert werden als in 15ms übertragen werden können\&. Ist der Datenstrom beschädigt! Maximum wird berechnet: 15 ms / 10 bits (8 data + start + stop) * Bautrate Syntax: [148] [Number of packets] [Packet ID 1] [Packet ID 2] [Packet ID 3] etc\&. Syntax der Antwort: [19][N-bytes][Packet ID 1][Packet 1 data\&.\&.\&.][Packet ID 2][Packet 2 data\&.\&.\&.][Checksum] 
.SS "#define ROOMBA_STREAM_PAUSE_RESUME   150"
Pausiert oder Startet einen Passierten Steam Syntax: [150][Stream State 0-1] 
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Roomba Library aus dem Quellcode\&.
