.TH "Sensor Gruppen Daten" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sensor Gruppen Daten \- 
.SS "Makrodefinitionen"

.in +1c
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_0\fP   0"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_0_SIZE\fP   26"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_0_START\fP   7"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_0_STOP\fP   26"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_1\fP   1"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_1_SIZE\fP   10"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_1_START\fP   7"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_1_STOP\fP   16"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_2\fP   2"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_2_SIZE\fP   6"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_2_START\fP   17"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_2_STOP\fP   20"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_3\fP   3"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_3_SIZE\fP   10"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_3_START\fP   21"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_3_STOP\fP   26"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_4\fP   4"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_4_SIZE\fP   14"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_4_START\fP   27"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_4_STOP\fP   34"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_5\fP   5"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_5_SIZE\fP   12"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_5_START\fP   35"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_5_STOP\fP   42"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_6\fP   6"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_6_SIZE\fP   52"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_6_START\fP   7"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_6_STOP\fP   42"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_100\fP   100"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_100_SIZE\fP   93"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_100_START\fP   7"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_100_STOP\fP   71"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_101\fP   101"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_101_SIZE\fP   28"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_101_START\fP   43"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_101_STOP\fP   58"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_106\fP   106"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_106_SIZE\fP   12"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_106_START\fP   46"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_106_STOP\fP   51"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_107\fP   107"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_107_SIZE\fP   9"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_107_START\fP   54"
.br
.ti -1c
.RI "#define \fBROOMBA_SENSOR_GROUP_107_STOP\fP   58"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SH "Makro-Dokumentation"
.PP 
.SS "#define ROOMBA_SENSOR_GROUP_0   0"
Sensor ID 7 - 26 
.SS "#define ROOMBA_SENSOR_GROUP_0_SIZE   26"

.SS "#define ROOMBA_SENSOR_GROUP_0_START   7"

.SS "#define ROOMBA_SENSOR_GROUP_0_STOP   26"

.SS "#define ROOMBA_SENSOR_GROUP_1   1"
Sensor ID 7 - 16 
.SS "#define ROOMBA_SENSOR_GROUP_100   100"
Sensor ID 7-58 
.SS "#define ROOMBA_SENSOR_GROUP_100_SIZE   93"

.SS "#define ROOMBA_SENSOR_GROUP_100_START   7"

.SS "#define ROOMBA_SENSOR_GROUP_100_STOP   71"

.SS "#define ROOMBA_SENSOR_GROUP_101   101"
Sensor ID 43 - 58 
.SS "#define ROOMBA_SENSOR_GROUP_101_SIZE   28"

.SS "#define ROOMBA_SENSOR_GROUP_101_START   43"

.SS "#define ROOMBA_SENSOR_GROUP_101_STOP   58"

.SS "#define ROOMBA_SENSOR_GROUP_106   106"
Sensor ID 43 - 51 
.SS "#define ROOMBA_SENSOR_GROUP_106_SIZE   12"

.SS "#define ROOMBA_SENSOR_GROUP_106_START   46"

.SS "#define ROOMBA_SENSOR_GROUP_106_STOP   51"

.SS "#define ROOMBA_SENSOR_GROUP_107   107"
Sensor ID 54 - 58 
.SS "#define ROOMBA_SENSOR_GROUP_107_SIZE   9"

.SS "#define ROOMBA_SENSOR_GROUP_107_START   54"

.SS "#define ROOMBA_SENSOR_GROUP_107_STOP   58"

.SS "#define ROOMBA_SENSOR_GROUP_1_SIZE   10"

.SS "#define ROOMBA_SENSOR_GROUP_1_START   7"

.SS "#define ROOMBA_SENSOR_GROUP_1_STOP   16"

.SS "#define ROOMBA_SENSOR_GROUP_2   2"
Sensor ID 17 - 20 
.SS "#define ROOMBA_SENSOR_GROUP_2_SIZE   6"

.SS "#define ROOMBA_SENSOR_GROUP_2_START   17"

.SS "#define ROOMBA_SENSOR_GROUP_2_STOP   20"

.SS "#define ROOMBA_SENSOR_GROUP_3   3"
Sensor ID 21 - 26 
.SS "#define ROOMBA_SENSOR_GROUP_3_SIZE   10"

.SS "#define ROOMBA_SENSOR_GROUP_3_START   21"

.SS "#define ROOMBA_SENSOR_GROUP_3_STOP   26"

.SS "#define ROOMBA_SENSOR_GROUP_4   4"
Sensor ID 27 - 34 
.SS "#define ROOMBA_SENSOR_GROUP_4_SIZE   14"

.SS "#define ROOMBA_SENSOR_GROUP_4_START   27"

.SS "#define ROOMBA_SENSOR_GROUP_4_STOP   34"

.SS "#define ROOMBA_SENSOR_GROUP_5   5"
Sensor ID 35 - 42 
.SS "#define ROOMBA_SENSOR_GROUP_5_SIZE   12"

.SS "#define ROOMBA_SENSOR_GROUP_5_START   35"

.SS "#define ROOMBA_SENSOR_GROUP_5_STOP   42"

.SS "#define ROOMBA_SENSOR_GROUP_6   6"
Sensor ID 7 - 42 
.SS "#define ROOMBA_SENSOR_GROUP_6_SIZE   52"

.SS "#define ROOMBA_SENSOR_GROUP_6_START   7"

.SS "#define ROOMBA_SENSOR_GROUP_6_STOP   42"

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Roomba Library aus dem Quellcode\&.
