.TH "/home/andreas/roomba/lib/includes/roomba_repeat.h" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/andreas/roomba/lib/includes/roomba_repeat.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <roomba_def\&.h>\fP
.br

.SS "Makrodefinitionen"

.in +1c
.ti -1c
.RI "#define \fBROOMBA_REPEAT_ERROR_NOT_STARTED\fP   -2"
.br
.in -1c
.SS "Funktionen"

.in +1c
.ti -1c
.RI "int8_t \fBroomba_repeat_init\fP (int8_t(*c)(\fBroombaCommand_t\fP *command), int8_t(*thread_start)(uint16_t ms), int8_t(*thread_stop)())"
.br
.ti -1c
.RI "int8_t \fBroomba_repeat\fP ()"
.br
.ti -1c
.RI "int8_t \fBroomba_repeat_start\fP (\fBroombaCommand_t\fP *c, uint16_t ms)"
.br
.ti -1c
.RI "int8_t \fBroomba_repeat_stop\fP ()"
.br
.in -1c
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Roomba Library aus dem Quellcode\&.
