.TH "Mode Kommandos" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mode Kommandos \- 
.SS "Makrodefinitionen"

.in +1c
.ti -1c
.RI "#define \fBROOMBA_SAFE\fP   131"
.br
.ti -1c
.RI "#define \fBROOMBA_FULL\fP   132"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SH "Makro-Dokumentation"
.PP 
.SS "#define ROOMBA_FULL   132"
Wechselt in den Full Modus 
.SS "#define ROOMBA_SAFE   131"
Wechselt in den Safe Modus 
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Roomba Library aus dem Quellcode\&.
