.TH "Start Kommandos" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Start Kommandos \- 
.SS "Makrodefinitionen"

.in +1c
.ti -1c
.RI "#define \fBROOMBA_START\fP   128"
.br
.ti -1c
.RI "#define \fBROOMBA_BAUD\fP   129"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SH "Makro-Dokumentation"
.PP 
.SS "#define ROOMBA_BAUD   129"
Setzt eine neue Baud Rate\&. Dieser Befehl erwartet einen weiteren Byte der die Baud Rate bestimmt\&. Es muss 100 ms gewarnt werden bevor der Roomba mit der neuen Bautrate angesprochen werden kann\&.
.PP
Nicht Funktionsfähig auf dem Roomba 780 
.SS "#define ROOMBA_START   128"
Setzt den Roomba von dem Off Modus in den Passive Modus 
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Roomba Library aus dem Quellcode\&.
