.TH "sensorString" 3 "Fre Okt 11 2013" "Roomba Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sensorString \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <roomba_print\&.h>\fP
.SS "Datenfelder"

.in +1c
.ti -1c
.RI "uint8_t \fBsensorID\fP"
.br
.ti -1c
.RI "char * \fBsensorStr\fP"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Aufbau eines Sensor Strings 
.SH "Dokumentation der Datenelemente"
.PP 
.SS "uint8_t sensorString::sensorID"
Sensor ID 
.SS "char* sensorString::sensorStr"
Sensor ID als String 

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Roomba Library aus dem Quellcode\&.
